#server:
 # port: 9090

#spring:
 # datasource:
  #  username: alejo
   # password: PjC9eVkzv5qyn4Nl
    #url: jdbc:mysql://localhost:3306/prueba
 #   driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
  #  show-sql: true
    #hibernate:
   #   ddl-auto: create-drop
  #  properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
 #   database-platform: org.hibernate.dialect.MySQL8Dialect